name: Trigger Update Citations (Main)

on:
  schedule:
    - cron: "0 0 * * 1" # Monday
    - cron: "0 0 * * 3" # Wednesday
    - cron: "0 0 * * 5" # Friday
    
  # Optional: Allow manual trigger from main
  workflow_dispatch:

jobs:
  call-dev-workflow:
    # SYNTAX: owner/repo/path/to/file@branch_name
    uses: SustainableUrbanSystemsLab/SustainableUrbanSystemsLab.github.io/.github/workflows/update-citations.yml@dev
    
    # Pass secrets if your workflow pushes changes or uses tokens
    secrets: inherit